#!/usr/bin/env bash

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/TeamUltroid/Ultroid
    cd Ultroid
fi
bash resources/startup/termux.sh
